repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--fix]
        exclude: (?x)^(results/|docs/references/)
      - id: ruff-format
        exclude: (?x)^(results/|docs/references/)
