"""Live CDS Hooks 1.0 HTTP service.

CDS Hooks (`https://cds-hooks.org/`) is the EHR-side standard Epic, Cerner,
Meditech, and Allscripts use to invoke decision-support services. The
service exposes two endpoints:

- ``GET /cds-services`` — discovery document listing services.
- ``POST /cds-services/{service-id}`` — invocation; the EHR passes a
  ``hook``, ``hookInstance``, ``context`` (incl. ``patientId`` and the
  current ``encounterId``) and a ``prefetch`` payload (typically the
  patient's FHIR resources). The service responds with zero or more
  ``cards`` for the EHR to render.

This implementation is intentionally stdlib-only (no FastAPI) so the
Superpower can run anywhere Python runs without pulling extra deps. The
trade-off is no async; for a hackathon submission a single-threaded
``ThreadingHTTPServer`` is more than enough.

The service registers ONE hook today: ``encounter-start``. When fired,
the agent scores the prefetched FHIR Bundle and returns a CDS Hooks card
generated by ``agents_assemble.agent_triage.cds_hooks``.

Run:

    python -m healthcraft.agents_assemble.cds_hooks_server --port 8080

Test discovery:

    curl -s http://localhost:8080/cds-services | jq .

Test invocation (fixture POST):

    curl -s -XPOST http://localhost:8080/cds-services/healthcraft-ed-triage \
         -H 'content-type: application/json' \
         -d @src/healthcraft/agents_assemble/demo/stemi_cds_hooks.json | jq .
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import logging
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any

from healthcraft.agents_assemble.agent_triage.agent import create_triage_agent
from healthcraft.agents_assemble.agent_triage.cds_hooks import to_cds_hooks_response
from healthcraft.agents_assemble.superpower_decision_rules.phi_scrubber import scrub_bundle
from healthcraft.entities.decision_rules import load_decision_rules
from healthcraft.world.state import WorldState

logger = logging.getLogger("agents_assemble.cds_hooks_server")


SERVICE_ID = "healthcraft-ed-triage"

# CDS Hooks discovery payload — the EHR fetches this on registration.
SERVICE_DESCRIPTOR: dict[str, Any] = {
    "hook": "encounter-start",
    "title": "Mercy Point ED Triage",
    "description": (
        "Scores the most-relevant ED decision rule for an incoming encounter "
        "(HEART, Wells PE/DVT, qSOFA, CURB-65, PERC, ABCD2, NEWS2, ...) and "
        "returns an advisory CDS Hooks card with the recommended disposition, "
        "a safety-gate flag, and a SHA-256 of the input Bundle for provenance."
    ),
    "id": SERVICE_ID,
    "prefetch": {
        # The EHR is asked to send these resources alongside the hook so the
        # service does not need to call back into the FHIR server itself.
        "patient": "Patient/{{context.patientId}}",
        "encounter": "Encounter/{{context.encounterId}}",
        "conditions": "Condition?subject={{context.patientId}}",
        "observations": ("Observation?subject={{context.patientId}}&_sort=-date&_count=20"),
    },
}


def _build_world() -> WorldState:
    """Construct a singleton world preloaded with the 30-rule library."""
    w = WorldState()
    for rid, rule in load_decision_rules().items():
        w.put_entity("decision_rule", rid, rule)
    return w


def _bundle_from_prefetch(prefetch: dict[str, Any] | None) -> dict[str, Any]:
    """Compose a single FHIR Bundle from the EHR's prefetch payload.

    CDS Hooks prefetch values are individual resources or Bundles. Either
    is accepted; we normalize to a single ``Bundle.entry[*].resource`` shape
    so downstream code only deals with Bundles.
    """
    entries: list[dict[str, Any]] = []
    for value in (prefetch or {}).values():
        if not isinstance(value, dict):
            continue
        if value.get("resourceType") == "Bundle":
            for e in value.get("entry") or []:
                resource = e.get("resource") if isinstance(e, dict) else None
                if isinstance(resource, dict):
                    entries.append({"resource": resource})
        elif "resourceType" in value:
            entries.append({"resource": value})
    return {"resourceType": "Bundle", "type": "collection", "entry": entries}


class _Handler(BaseHTTPRequestHandler):
    server_version = "agents-assemble-cds-hooks/0.1"

    # Lazily attached by serve(); makes mocking trivial in tests.
    world: WorldState | None = None

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _send_json(self, status: int, payload: dict[str, Any]) -> None:
        body = json.dumps(payload, default=str).encode("utf-8")
        self.send_response(status)
        self.send_header("content-type", "application/json")
        self.send_header("content-length", str(len(body)))
        # CORS — allow EHR/test fetches from a browser tab.
        self.send_header("access-control-allow-origin", "*")
        self.send_header("access-control-allow-methods", "GET, POST, OPTIONS")
        self.send_header("access-control-allow-headers", "content-type")
        self.end_headers()
        self.wfile.write(body)

    def _read_json_body(self) -> dict[str, Any]:
        length = int(self.headers.get("content-length") or 0)
        if length <= 0:
            return {}
        raw = self.rfile.read(length)
        try:
            parsed = json.loads(raw)
        except json.JSONDecodeError:
            return {}
        return parsed if isinstance(parsed, dict) else {}

    # ------------------------------------------------------------------
    # HTTP methods
    # ------------------------------------------------------------------

    def do_OPTIONS(self) -> None:  # noqa: N802 — http handler convention
        self._send_json(HTTPStatus.NO_CONTENT, {})

    def do_GET(self) -> None:  # noqa: N802
        if self.path.rstrip("/") == "/cds-services":
            self._send_json(HTTPStatus.OK, {"services": [SERVICE_DESCRIPTOR]})
            return
        if self.path.rstrip("/") in ("", "/", "/healthz"):
            self._send_json(HTTPStatus.OK, {"status": "ok", "service": SERVICE_ID})
            return
        self._send_json(HTTPStatus.NOT_FOUND, {"error": "not_found", "path": self.path})

    def do_POST(self) -> None:  # noqa: N802
        if self.path.rstrip("/") != f"/cds-services/{SERVICE_ID}":
            self._send_json(HTTPStatus.NOT_FOUND, {"error": "unknown_service", "path": self.path})
            return

        body = self._read_json_body()
        bundle = scrub_bundle(_bundle_from_prefetch(body.get("prefetch")))
        if not (bundle.get("entry") or []):
            self._send_json(
                HTTPStatus.OK,
                {
                    "cards": [
                        {
                            "summary": "No prefetch data — agent could not score.",
                            "indicator": "info",
                            "source": {"label": "Mercy Point Triage Agent"},
                            "detail": (
                                "Configure CDS Hooks prefetch with patient + encounter + "
                                "conditions + recent observations so the agent can apply "
                                "a decision rule."
                            ),
                        }
                    ]
                },
            )
            return

        agent = create_triage_agent(self.world)
        plan = agent.run(
            bundle,
            sharp={
                "contextId": str(body.get("hookInstance") or ""),
                "correlationId": str(body.get("hookInstance") or ""),
            },
        )
        response = to_cds_hooks_response(dataclasses.asdict(plan))
        self._send_json(HTTPStatus.OK, response)

    # Quieter access log — drop the default stderr spam during tests.
    def log_message(self, format: str, *args: Any) -> None:
        logger.debug("%s - %s", self.address_string(), format % args)


def serve(port: int = 8080, host: str = "0.0.0.0") -> ThreadingHTTPServer:
    """Start the CDS Hooks HTTP service. Returns the server (caller closes)."""
    handler = _Handler
    handler.world = _build_world()
    server = ThreadingHTTPServer((host, port), handler)
    logger.info("CDS Hooks service listening on %s:%d/cds-services", host, port)
    return server


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--port", type=int, default=8080)
    parser.add_argument("--host", default="0.0.0.0")
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(name)s %(message)s")
    server = serve(port=args.port, host=args.host)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
