"""Source-concordance verification for explicitly inventoried development cases.

Expected rows are supplied authored data, never generated by a controller or
fixture builder. This verifier rechecks their source bindings and mechanical
scope. Registry authentication belongs to the hash-pinned casebook loader;
matching digests here do not establish independent or clinical adjudication.
"""

from __future__ import annotations

import re
from collections import Counter
from copy import deepcopy

from healthcraft.reconciliation.oracle import (
    _digest,
    _indexed,
    _json,
    _require,
    _same,
    _verify_reconciliation,
)
from healthcraft.temporal import instant_key

CASE_VERSION = "healthcraft-reconciliation-case/v2"
EXECUTION_VERSION = "healthcraft-reconciliation-execution/v2"
VERIFICATION_VERSION = "healthcraft-reconciliation-verification/v2"
_BINDINGS = {
    "case_id",
    "scenario_family_id",
    "casebook_sha256",
    "scenario_sha256",
    "expectations_sha256",
}
_ROW_FIELDS = {
    "active_orders": ({"source_id", "order_id", "item", "status", "time"}, set()),
    "current_management": ({"source_id", "item", "status", "time"}, {"kind"}),
    "treatments_given": (
        {"source_id", "item", "reported_status", "event_time"},
        {"event_id", "reporter"},
    ),
    "imaging_pending": (
        {"source_id", "study_id", "modality", "body_part", "status", "time"},
        set(),
    ),
}


def _keys(value, required, optional=frozenset()):
    _require(
        type(value) is dict
        and required <= value.keys()
        and not value.keys() - (required | optional),
        "Missing or unsupported contract fields",
    )


def _text(value):
    _require(type(value) is str and bool(value.strip()), "Expected nonempty contract text")


def _identifier(value, prefix):
    _require(
        type(value) is str
        and re.fullmatch(rf"{prefix}-(?:[A-F0-9]{{8}}|[A-F0-9]{{12}})", value) is not None,
        "Invalid entity identifier",
    )


def _timestamp(value):
    if value is not None:
        _require(type(value) is str, "Source time must be an aware string or null")
        instant_key(value)


def _part(value):
    return str(value).replace("~", "~0").replace("/", "~1")


def _source_contract(scenario):
    """Read source literals directly; no projector or reference controller imports."""
    _keys(scenario, {"schema_version", "id", "clock", "target", "patients", "encounters"})
    _require(
        scenario["schema_version"] == "healthcraft-reconciliation-scenario/v2",
        "Wrong scenario schema",
    )
    _text(scenario["id"])
    _timestamp(scenario["clock"])
    _require(scenario["clock"] is not None, "World clock cannot be unknown")
    whole, fraction = instant_key(scenario["clock"])
    _require(len(fraction) <= 6, "World clock precision exceeds the runtime")
    clock = whole.replace(microsecond=int(fraction.ljust(6, "0") or "0")).isoformat()
    _keys(scenario["target"], {"patient_id", "encounter_id"})
    _identifier(scenario["target"]["patient_id"], "PAT")
    _identifier(scenario["target"]["encounter_id"], "ENC")
    _require(
        type(scenario["patients"]) is list and 1 <= len(scenario["patients"]) <= 8,
        "Patient roster outside v2 bounds",
    )
    _require(
        type(scenario["encounters"]) is list and 1 <= len(scenario["encounters"]) <= 16,
        "Encounter roster outside v2 bounds",
    )
    patients = _indexed(scenario["patients"], "id")
    names, mrns = set(), set()
    for patient in patients.values():
        _keys(
            patient,
            {"id", "mrn", "first_name", "last_name", "date_of_birth", "sex", "prior_visit_ids"},
        )
        _identifier(patient["id"], "PAT")
        for field in ("mrn", "first_name", "last_name"):
            _text(patient[field])
        _require(
            patient["date_of_birth"] is None and type(patient["sex"]) is str,
            "Unsupported initial demographic contract",
        )
        names.add((patient["first_name"], patient["last_name"]))
        _require(patient["mrn"] not in mrns, "Duplicate patient MRN")
        mrns.add(patient["mrn"])
        prior = patient["prior_visit_ids"]
        _require(
            type(prior) is list and all(type(value) is str for value in prior),
            "Invalid prior encounter links",
        )
        _require(len(prior) == len(set(prior)), "Duplicate prior encounter link")
    _require(len(names) == 1, "V2 reference scope is one same-name patient cohort")
    encounters = _indexed(scenario["encounters"], "id")
    counts, source_rows = Counter(), []
    for encounter in encounters.values():
        _keys(encounter, {"id", "patient_id", "chief_complaint", "arrival_time", "patient_data"})
        _identifier(encounter["id"], "ENC")
        _identifier(encounter["patient_id"], "PAT")
        _require(encounter["patient_id"] in patients, "Encounter belongs to an absent patient")
        _text(encounter["chief_complaint"])
        _timestamp(encounter["arrival_time"])
        counts[encounter["patient_id"]] += 1
        _require(counts[encounter["patient_id"]] <= 9, "Encounter search would be saturated")
        data = encounter["patient_data"]
        _keys(data, set(), set(_ROW_FIELDS))
        for collection, contents in data.items():
            imaging = collection == "imaging_pending"
            _require(
                type(contents) is (dict if imaging else list), "Unsupported source collection shape"
            )
            entries = contents.items() if imaging else enumerate(contents)
            for label, row in entries:
                required, optional = _ROW_FIELDS[collection]
                _keys(row, required, optional)
                _require(
                    type(row["source_id"]) is str
                    and re.fullmatch(r"SRC-[A-Z][0-9]{2}", row["source_id"]) is not None,
                    "Invalid source identity",
                )
                for key, value in row.items():
                    if key in {"time", "event_time"}:
                        _timestamp(value)
                    elif key == "status" and value is None:
                        continue
                    else:
                        _text(value)
                source_rows.append(
                    {
                        "source_id": row["source_id"],
                        "patient_id": encounter["patient_id"],
                        "encounter_id": encounter["id"],
                        "source_collection": collection,
                        "source_path": f"/{collection}/{_part(label)}",
                        "source": row,
                    }
                )
    _require(1 <= len(source_rows) <= 128, "Source count outside v2 bounds")
    sources = _indexed(source_rows, "source_id")
    target = scenario["target"]
    _require(
        target["encounter_id"] in encounters
        and encounters[target["encounter_id"]]["patient_id"] == target["patient_id"],
        "Target ownership mismatch",
    )
    for patient in patients.values():
        for prior in patient["prior_visit_ids"]:
            _require(
                prior in encounters
                and encounters[prior]["patient_id"] == patient["id"]
                and prior != target["encounter_id"],
                "Wrong prior encounter ownership",
            )
    return sources, clock


def _validate_case(case):
    _json(case)
    _keys(
        case,
        {
            "schema_version",
            "case_id",
            "scenario_family_id",
            "exposure",
            "label_status",
            "casebook_sha256",
            "scenario_sha256",
            "expectations_sha256",
            "scenario",
            "expectations",
            "designated_control",
        },
    )
    _require(case["schema_version"] == CASE_VERSION, "Wrong case schema")
    _require(
        case["exposure"] == "development"
        and case["label_status"] == "engineering_authored_independent_review_pending",
        "Unsupported case/label provenance",
    )
    for key in ("case_id", "scenario_family_id", "designated_control"):
        _text(case[key])
    _require(
        re.fullmatch(r"REC2-[0-9]{3}", case["case_id"]) is not None,
        "Invalid case ID syntax",
    )
    for key in ("casebook_sha256", "scenario_sha256", "expectations_sha256"):
        _require(
            type(case[key]) is str and re.fullmatch(r"[0-9a-f]{64}", case[key]) is not None,
            "Invalid case digest",
        )
    scenario, expected = case["scenario"], case["expectations"]
    _require(
        _digest(scenario) == case["scenario_sha256"]
        and _digest(expected) == case["expectations_sha256"],
        "Case content identity mismatch",
    )
    sources, clock = _source_contract(scenario)
    _require(
        scenario["id"] == f"synthetic-ed-reconciliation/v2/{case['case_id']}",
        "Case ID does not identify its bound scenario",
    )
    _keys(
        expected,
        {
            "schema_version",
            "scenario_id",
            "scenario_sha256",
            "target",
            "sources",
            "observation_source_ids",
            "unresolved_conflicts",
            "scope_exclusions",
        },
    )
    _require(
        expected["schema_version"] == "healthcraft-reconciliation-expectations/v2"
        and expected["scenario_id"] == scenario["id"]
        and expected["scenario_sha256"] == case["scenario_sha256"],
        "Expectations scenario binding mismatch",
    )
    _require(
        _same(expected["target"], scenario["target"]), "Expected target differs from source target"
    )
    _require(
        _same(_indexed(expected["sources"], "source_id"), sources),
        "Expected ledger differs from exact source rows",
    )
    target = scenario["target"]
    selected = {
        key
        for key, row in sources.items()
        if row["patient_id"] == target["patient_id"]
        and row["encounter_id"] == target["encounter_id"]
    }
    observed = expected["observation_source_ids"]
    _require(
        type(observed) is list and all(type(value) is str for value in observed) and bool(observed),
        "Missing observation labels",
    )
    _require(
        len(observed) == len(set(observed)) and set(observed) == selected,
        "Observation labels must cover each target source exactly once",
    )
    excluded = _indexed(expected["scope_exclusions"], "source_id")
    _require(
        set(excluded) == sources.keys() - selected,
        "Scope exclusions must cover each other source exactly once",
    )
    for identifier, row in excluded.items():
        source = sources[identifier]
        _require(
            _same(
                row,
                {
                    "source_id": identifier,
                    "patient_id": source["patient_id"],
                    "encounter_id": source["encounter_id"],
                    "reason": "other_encounter"
                    if source["patient_id"] == target["patient_id"]
                    else "other_patient",
                },
            ),
            "Scope exclusion attribution mismatch",
        )
    # Validate literal engineering conflict labels, not which clinical report is
    # true. Every same-event source participates; no majority resolution.
    events = {}
    for identifier in selected:
        source = sources[identifier]["source"]
        if "event_id" in source:
            events.setdefault(source["event_id"], []).append(identifier)
    conflicts = _indexed(expected["unresolved_conflicts"], "event_id")
    conflicting_events = {
        event
        for event, ids in events.items()
        if {"administered", "not_administered"}
        <= {sources[identifier]["source"].get("reported_status") for identifier in ids}
    }
    _require(
        set(conflicts) == conflicting_events,
        "Conflict labels do not match supported literal disagreement groups",
    )
    for event, row in conflicts.items():
        _keys(row, {"event_id", "source_ids", "field"})
        ids = row["source_ids"]
        _require(
            type(ids) is list and all(type(identifier) is str for identifier in ids),
            "Malformed conflict source labels",
        )
        _require(
            len(ids) == len(set(ids))
            and set(ids) == set(events[event])
            and row["field"] == "reported_status",
            "Conflict sources/field mismatch",
        )
    return sources, selected, clock


def verify_case(case: dict, evidence: dict) -> dict:
    """Recheck an inventoried case and native evidence without a clinical score.

    Caller must obtain the case through the hash-pinned casebook loader. This
    function independently checks its internal hashes/labels and execution
    binding; it cannot authenticate the supplied registry digest in isolation.
    """
    result = {
        "schema_version": VERIFICATION_VERSION,
        "status": "provenance_error",
        "checks": {
            key: False
            for key in (
                "provenance",
                "source_fidelity",
                "persisted_action",
                "readback",
                "execution_complete",
            )
        },
        "mechanical_passed": False,
        "benchmark_score": None,
        "benchmark_comparable": False,
        "grading_complete": False,
        "coverage": {
            "expected_sources": None,
            "target_observations": None,
            "clinical_criteria": 0,
            "safety_criteria": 0,
        },
        "errors": [],
        "expectations_sha256": None,
        "case_binding": None,
        "limitations": [
            "Engineering-authored development labels; independent review remains pending.",
            "Hashes establish content consistency, not registry/execution authenticity.",
        ],
    }
    try:
        sources, selected, clock = _validate_case(case)
        _require(type(evidence) is dict, "Evidence must be an object")
        _json(evidence)
        binding = {key: case[key] for key in _BINDINGS}
        _require(_same(evidence.get("case_binding"), binding), "Execution case binding mismatch")
        result = _verify_reconciliation(
            case["scenario"],
            case["expectations"],
            evidence,
            expected_digest=case["expectations_sha256"],
            execution_schema=EXECUTION_VERSION,
            verification_schema=VERIFICATION_VERSION,
            expected_sources=len(sources),
            target_observations=len(selected),
            expected_clock=clock,
        )
        result["case_binding"] = deepcopy(binding)
        result["limitations"] = [
            "Engineering-authored development labels; independent review remains pending.",
            "Hashes establish content consistency, not registry/execution authenticity.",
        ]
    except (
        ValueError,
        TypeError,
        KeyError,
        IndexError,
        AttributeError,
        OverflowError,
        RecursionError,
    ) as exc:
        result["errors"].append({"axis": "provenance", "message": f"{type(exc).__name__}: {exc}"})
    return result
