"""Loss-mask derivation for multi-turn agentic RL.

In a multi-turn agentic rollout only POLICY-generated tokens may contribute
to the policy gradient. Tool-result, user, and system tokens were not
generated by the policy under training, so including them in the policy-
gradient loss corrupts the gradient. This is the convention adopted by
VerlTool, GTPO, and DAPO multi-turn recipes.

This module produces:

- :func:`role_loss_mask` — one int per :class:`Trajectory` turn; no tokenizer
  required. ``mask[i] = 1`` iff turn ``i`` is assistant-role; else ``0``.
  This is the CPU-dry-run-friendly form and is sufficient to express and
  test the contract.

- :func:`token_loss_mask` — one int per token. Tokenises each turn's content
  with a caller-provided tokenizer and concatenates with the appropriate
  per-token mask. This is the form the slime adapter passes to the
  Megatron policy-gradient loss.

- :func:`serialize_tool_result` — deterministic JSON serialisation
  (``sort_keys=True``) used to avoid retokenisation nondeterminism at turn
  boundaries (cf. zylos.ai agentic-RL guide). The existing agent loop's
  ``json.dumps(..., default=str)`` is not key-sorted; new RL rollouts should
  use this instead.

Trajectory role convention (per CLAUDE.md):
    ``assistant`` → 1; ``system``, ``user``, ``tool`` → 0.
"""

from __future__ import annotations

import json
from typing import Any, Callable

from healthcraft.trajectory import Trajectory, TrajectoryTurn

_POLICY_ROLE = "assistant"


def role_loss_mask(trajectory: Trajectory) -> list[int]:
    """Return one mask value per turn (1 = policy-generated, 0 = environment).

    Length equals ``len(trajectory.turns)``. Stable under trajectory replay:
    given the same captured turns, the mask is byte-identical.
    """
    return [1 if t.role == _POLICY_ROLE else 0 for t in trajectory.turns]


def serialize_tool_result(result: Any) -> str:
    """Deterministically serialise a tool result to a string.

    ``json.dumps`` with ``sort_keys=True`` so equivalent dicts always
    tokenise to the same byte sequence. Plain strings pass through
    unchanged so an already-serialised tool result is not double-encoded.
    """
    if isinstance(result, str):
        return result
    return json.dumps(result, default=str, sort_keys=True, ensure_ascii=False)


def token_loss_mask(
    trajectory: Trajectory,
    tokenize: Callable[[str], list[int]],
) -> tuple[list[int], list[int]]:
    """Tokenise the trajectory and return ``(tokens, per-token loss mask)``.

    Args:
        trajectory: The captured trajectory.
        tokenize: A callable mapping a string to a list of token ids.
            Provided by the caller — typically the slime/SGLang tokenizer.
            MUST be deterministic for the same input.

    Returns:
        A pair ``(tokens, mask)`` of equal length. ``mask[i] == 1`` iff
        token ``i`` originated in an assistant turn.

    Notes:
        - Tool-call structures inside an assistant turn (function-call JSON)
          ARE part of the policy's output and receive ``mask = 1``.
        - Tool-role turns receive ``mask = 0`` even when their content was
          produced by :func:`serialize_tool_result`.
    """
    tokens: list[int] = []
    mask: list[int] = []
    for turn in trajectory.turns:
        chunk = _turn_to_text(turn)
        if not chunk:
            continue
        chunk_tokens = tokenize(chunk)
        if not chunk_tokens:
            continue
        m = 1 if turn.role == _POLICY_ROLE else 0
        tokens.extend(chunk_tokens)
        mask.extend([m] * len(chunk_tokens))
    return tokens, mask


def _turn_to_text(turn: TrajectoryTurn) -> str:
    """Render a turn to the same string the policy would have seen/emitted.

    Assistant turns: text content followed by a deterministic rendering of
    any tool calls. Tool-role turns: deterministic JSON of their content.
    System/user turns: their content verbatim.
    """
    if turn.role == _POLICY_ROLE:
        parts: list[str] = []
        if turn.content:
            parts.append(turn.content)
        for tc in turn.tool_calls:
            payload = {"name": tc.get("name", ""), "arguments": tc.get("arguments", {})}
            parts.append(serialize_tool_result(payload))
        return "\n".join(parts)
    if turn.role == "tool":
        # Tool turns arrive as already-serialised JSON strings from the agent
        # loop. Parse-and-reserialise through serialize_tool_result so the
        # tokenised representation is deterministic regardless of the
        # original ``json.dumps`` key order. Falls back to the raw content
        # for non-JSON payloads (best-effort — historical trajectories).
        if turn.content:
            try:
                parsed = json.loads(turn.content)
            except (json.JSONDecodeError, TypeError):
                return turn.content
            return serialize_tool_result(parsed)
        return turn.content
    return turn.content
