"""Public dataclass types for the HealthCraft RL coupling.

These types are the contract between HealthCraft (env + reward) and the
external RL trainer (slime / verl). They intentionally avoid framework-
specific imports so HealthCraft stays CPU-installable and independent of
any single training stack.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from healthcraft.trajectory import Trajectory


@dataclass(frozen=True)
class RolloutResult:
    """Outcome of one episode rollout against :class:`HealthCraftEnv`.

    Returned by :meth:`healthcraft.rl.env.HealthCraftEnv.rollout`. Carries the
    full :class:`Trajectory` plus the loss mask the policy gradient must apply
    (1 for policy-generated tokens, 0 for environment/tool tokens).

    The ``reward`` field is populated by
    :func:`healthcraft.rl.reward.compute_training_reward` after the rollout
    completes — this dataclass is the rollout-side artifact and does not
    compute reward itself.
    """

    task_id: str
    episode_seed: int
    policy_model: str
    trajectory: Trajectory
    # Per-turn mask: 1 if the turn was generated by the policy (assistant),
    # 0 otherwise. Length equals ``len(trajectory.turns)``. Always populated.
    turn_loss_mask: tuple[int, ...] = ()
    # Per-token mask. Populated only when the rollout was tokenised at capture
    # time (e.g. by the slime adapter). Empty for the CPU dry-run path.
    token_loss_mask: tuple[int, ...] = ()
    tokens: tuple[int, ...] = ()
    # Set by ``compute_training_reward`` after the rollout. 0.0 means
    # "reward not yet computed", which is distinguishable from a hard-gate
    # zero only by inspecting ``TrainingRewardResult.safety_gate_passed``.
    reward: float = 0.0
    error: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class TrainingRewardResult:
    """Decomposed training reward returned by ``compute_training_reward``.

    The scalar ``reward`` is what enters the GRPO/DAPO advantage. The
    breakdown is essential for the anti-Goodhart / prevalence-drift /
    judge-kappa canaries — those instruments read which component drove the
    signal, not just the final number.

    This is intentionally a SEPARATE type from
    :class:`healthcraft.tasks.evaluator.TaskResult`. Eq. 1 evaluation reward
    is untouched; this type is read only by the RL training loop.
    """

    reward: float
    safety_gate_passed: bool
    r_verifiable: float
    r_judge: float
    r_process: float
    n_safety: int
    n_verifiable: int
    n_restraint: int
    n_restraint_violated: int
    n_judge_used: int
    n_judge_abstained: int
    evidence: dict[str, str] = field(default_factory=dict)
